services:
  doctrine_encrypt.encryptor:
    class: "%doctrine_encrypt.encryptor_class_name%"
    arguments:
      - '@=service("doctrine_encrypt.secret_factory").getSecret(parameter("doctrine_encrypt.encryptor_class_name"))'

  doctrine_encrypt.secret_factory:
    class: DoctrineEncryptBundle\Factories\SecretFactory
    arguments:
      $secretDirectory:      '%doctrine_encrypt.secret_directory_path%'
      $enableSecretCreation: '%doctrine_encrypt.enable_secret_generation%'