services:
    ambta_doctrine_attribute_reader:
        class: Ambta\DoctrineEncryptBundle\Mapping\AttributeReader

    ambta_doctrine_annotation_reader:
        class: Ambta\DoctrineEncryptBundle\Mapping\AttributeAnnotationReader
        arguments: ["@ambta_doctrine_attribute_reader", "@annotations.reader", "%kernel.cache_dir%"]

    ambta_doctrine_encrypt.orm_subscriber:
        class: Ambta\DoctrineEncryptBundle\Subscribers\DoctrineEncryptSubscriber
        arguments: ["@ambta_doctrine_annotation_reader", "@ambta_doctrine_encrypt.encryptor"]
        tags:
            -  { name: doctrine.event_subscriber }