services:
    doctrine_encrypt.encrypt_service:
        class: DoctrineEncryptBundle\Service\Encrypt
        arguments: ["@doctrine_encrypt.encryptor"]
        public: true

    doctrine_encrypt.command.decrypt.database:
        class: DoctrineEncryptBundle\Command\DoctrineDecryptDatabaseCommand
        tags: ['console.command']
        arguments:
            - "@doctrine.orm.entity_manager"
            - "@doctrine_encrypt.encrypt_service"

    doctrine_encrypt.command.encrypt.database:
        class: DoctrineEncryptBundle\Command\DoctrineEncryptDatabaseCommand
        tags: ['console.command']
        arguments:
            - "@doctrine.orm.entity_manager"
            - "@doctrine_encrypt.encrypt_service"

    doctrine_encrypt.command.encrypt.status:
        class: DoctrineEncryptBundle\Command\DoctrineEncryptStatusCommand
        tags: ['console.command']
        arguments:
            - "@doctrine.orm.entity_manager"
            - "@doctrine_encrypt.encrypt_service"
