# This file was heavily based on the ci-file from SymfonyCasts/verify-email-bundle
#
# See https://github.com/SymfonyCasts/verify-email-bundle
#     https://github.com/SymfonyCasts/verify-email-bundle/blob/main/.github/workflows/ci.yml

name: CI
on:
  push:
  pull_request:

jobs:
  tests:
    name: "Tests ${{ matrix.php-version }} ${{ matrix.dependency-versions }} deps ${{ matrix.dependency-versions }}"
    runs-on: ubuntu-18.04

    strategy:
      fail-fast: false
      matrix:
         php-version: ['7.2']
         composer-options: ['--prefer-stable']
         dependency-versions: ['highest']

        # normal, highest, non-dev installs
#        php-version: ['7.2', '7.3', '7.4', '8.0', '8.1']
#        composer-options: ['--prefer-stable']
#        dependency-versions: ['highest']
#        include:
#          # testing lowest PHP version with lowest dependencies
#          - php-version: '7.2.5'
#            dependency-versions: 'lowest'
#            composer-options: '--prefer-lowest'
#
#          # testing dev versions with highest PHP
#          - php-version: '8.1'
#            dependency-versions: 'highest'
#            composer-options: '' # allow dev deps

    steps:
      - name: "Checkout code"
        uses: "actions/checkout@v2"

      - name: "Install PHP"
        uses: "shivammathur/setup-php@v2"
        with:
          coverage: "none"
          php-version: "${{ matrix.php-version }}"

#      - name: Install Global Dependencies
#        run: |
#          composer global require --no-progress --no-scripts --no-plugins symfony/flex >=1.x
 
      - name: "Composer install"
        uses: "ramsey/composer-install@v1"
        with:
          dependency-versions: "${{ matrix.dependency-versions }}"
          composer-options: "--prefer-dist --no-progress"

      - name: Unit Tests
        run: vendor/bin/phpunit

      - name: Demo symfony4.4 - Install  dependencies
        uses: "ramsey/composer-install@v1"
        with:
          dependency-versions: "${{ matrix.dependency-versions }}"
          composer-options: "--prefer-dist --no-progress"
          working-directory: "demo/symfony4.4"

      - name: Demo symfony4.4 - Unit Tests
        run: demo/symfony4.4/vendor/bin/simple-phpunit -c demo/symfony4.4/phpunit.xml.dist

      - name: Demo symfony6.x - Install  dependencies
        uses: "ramsey/composer-install@v1"
        with:
          dependency-versions: "${{ matrix.dependency-versions }}"
          composer-options: "--prefer-dist --no-progress"
          working-directory: "demo/symfony6.x"

      - name: Demo symfony6.x - Unit Tests
        run: demo/symfony6.x/vendor/bin/simple-phpunit -c demo/symfony6.x/phpunit.xml.dist